language: elixir
elixir:
  - 1.4.0
  - 1.3.3
  - 1.3.2
otp_release:
  - 19.1
  - 19.0
  - 18.3
  - 18.2
sudo: false
script:
  - mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
